version: '3'

services:
  app:
    build: .
    command: gunicorn app.main:app --bind 0.0.0.0:8000
    container_name: tapic
    network_mode: host
    expose:
      - 8000
    # command: bash -c "uvicorn main:app"
    env_file:
      - .env 
    volumes:
      - ./tapic.app.db:/app/tapic.app.db:delegated

  nginx:
    build: ./nginx
    ports:
      - 1337:80
    depends_on:
      - app